#!/bin/sh

export PY_VERSION=3.7
export BROWSER=~/bin/browser.sh
export EDITOR=~/bin/editor.sh
export PATH="${HOME}/bin:${PATH}"

eval $(gpg-agent --daemon)
eval $(ssh-agent)

# Start audio before the apps
mixer pcm 100 vol 100
mixer -f /dev/mixer9 vol 100 pcm 100 mic 100
# Display
#xrandr --output default --primary --mode 1024x768 --pos 0x0 --rotate normal
#xrandr --output DisplayPort-0 --off --output DVI-D-0 --mode 1680x1050 --pos 0x0 --rotate normal --output HDMI-A-0 --mode 1680x1050 --pos 1680x0 --rotate normal


# Keyboard setup
xset r rate 180 30
setxkbmap -option "grp:lswitch" "us,hr"
xrdb ~/.Xdefaults
xmodmap ~/.xmodmap

# Apps
#urxvt -name weechat -e ~/bin/weechat.sh &
keepassxc &
unclutter &
xautolock -time 10 -locker ~/bin/slock.sh &
quiterrs &
~/bin/mail.sh &
offlineimap &
(sleep 2 && xsetroot) &
#gajim &
# skypeforlinux &
#/usr/sbin/mouseserver &
/opt/viber/Viber &
cat /dev/umidi0.0 >/dev/umidi1.0 &
#~/Files/server-ssh.sh &

exec i3
